apiVersion: compute.gcp.upbound.io/v1beta1
kind: Firewall
metadata:
  annotations:
    meta.upbound.io/id: compute/v1beta1/firewall
  labels:
    testing.upbound.io/name: example_firewall
  name: example-firewall
spec:
  forProvider:
    allow:
    - protocol: icmp
    - ports:
      - "80"
      - "8080"
      - 1000-2000
      protocol: tcp
    networkSelector:
      matchLabels:
        testing.upbound.io/name: example_firewall_network
    sourceTags:
    - web

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/id: compute/v1beta1/firewall
  labels:
    testing.upbound.io/name: example_firewall_network
  name: example-firewall-network
spec:
  forProvider:
    autoCreateSubnetworks: false